version: '3.7'
volumes:
    mongo_data:

services:

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27019:27017
    volumes: 
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
  bot:
    image: nazarpes7/wallpap
    container_name: WallPaperBot
    restart: always