version: '3.7'
volumes:
    mongo_data:

services:

  mongoR:
    image: mongo
    container_name: mongor
    restart: always
    ports:
      - 27019:27017
    volumes: 
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
  mongo-express:
  image: mongo-express
  container_name: Expressr
  restart: always
  ports:
    - 8082:8081
  environment:
    ME_CONFIG_MONGODB_ADMINUSERNAME: root
    ME_CONFIG_MONGODB_ADMINPASSWORD: password
  bot:
    image: nazarpes7/wallpap
    container_name: wallpapbot
    restart: always